### ISSUE TITLE
Cassandra 3.11

### ISSUE THREAD

**Issue by blop** [docker-library/cassandra#108]
Hello ;-)
Version 3.11 has been released a few days ago.

https://lists.apache.org/thread.html/b3afcf80349e29957704560a5931c5fbd7a8bc8126c3658fefb16cc1@%3Cdev.cassandra.apache.org%3E

https://git1-us-west.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=CHANGES.txt;hb=refs/tags/cassandra-3.11.0

https://issues.apache.org/jira/projects/CASSANDRA/versions/12339157/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

Can't wait to try the docker image :)

**Comment by yosifkit** [comment]
Ah, It looks like 3.11 replaces 3.10 (since it is now missing on the download page https://cassandra.apache.org/download/).  I'll make an update PR.

Thanks for the notice!
