### ISSUE TITLE
Nodes don't reconnect when one of the containers is restarted

### ISSUE THREAD

**Issue by tashburn** [docker-library/cassandra#11]
Hi There -

Thanks for producing these docker images. I hit a snag though. When start a 2-machine cluster on EC2, the dockerized cassandra nodes connect to each other and all seems fine. But when I restart one of the docker containers, the nodes don't reconnect.

Here are the commands I used to start the containers:

    docker run --name cass -d \
    --restart=on-failure:10 \
    -e CASSANDRA_BROADCAST_ADDRESS=172.30.0.35 \
    -e CASSANDRA_CLUSTER_NAME=spot \
    -p 7000:7000 \
    cassandra:latest

    docker run --name cass -d \
    --restart=on-failure:10 \
    -e CASSANDRA_BROADCAST_ADDRESS=172.30.1.116 \
    -e CASSANDRA_CLUSTER_NAME=spot \
    -p 7000:7000 \
    -e CASSANDRA_SEEDS=172.30.0.35 \
    cassandra:latest

Here's the nodetool status when they first connect:

    Datacenter: datacenter1
    =======================
    Status=Up/Down
    |/ State=Normal/Leaving/Joining/Moving
    --  Address       Load       Tokens  Owns (effective)  Host ID                               Rack
    UN  172.30.0.35   51.45 KB   256     100.0%            015e7e26-91ec-4bdc-b59b-aa29c35248e6  rack1
    UN  172.30.1.116  ?          256     100.0%            243efb28-02d4-4ded-8419-ce32a28186b8  rack1

When I run <pre><code>docker restart cass</code></pre> on either of the nodes, they don't reconnect:

<pre><code>
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens  Owns (effective)  Host ID                               Rack
UN  172.30.0.35   51.45 KB   256     100.0%            015e7e26-91ec-4bdc-b59b-aa29c35248e6  rack1
DN  172.30.1.116  51.51 KB   256     100.0%            243efb28-02d4-4ded-8419-ce32a28186b8  rack1
</code></pre>

Here's the last bit of log from the node I restarted:

<pre><code>
INFO  20:06:21 Enqueuing flush of local: 51479 (0%) on-heap, 0 (0%) off-heap
INFO  20:06:21 Writing Memtable-local@983239489(8566 serialized bytes, 259 ops, 0%/0% of on/off-heap limit)
INFO  20:06:21 OutboundTcpConnection using coalescing strategy DISABLED
INFO  20:06:21 Completed flushing /var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-9-Data.db (5277 bytes) for commitlog position ReplayPosition(segmentId=1435089979529, position=104922)
INFO  20:06:21 Handshaking version with /172.30.0.35
INFO  20:06:21 Node /172.30.1.116 state jump to normal
INFO  20:06:21 Node /172.30.0.35 has restarted, now UP
INFO  20:06:21 InetAddress /172.30.0.35 is now UP
INFO  20:06:21 Node /172.30.0.35 state jump to normal
INFO  20:06:21 Waiting for gossip to settle before accepting client requests...
INFO  20:06:21 Compacted 4 sstables to [/var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-10,].  6,295 bytes to 5,723 (~90% of original) in 251ms = 0.021745MB/s.  4 total partitions merged to 1.  Partition merge counts were {4:1, }
INFO  20:06:29 No gossip backlog; proceeding
INFO  20:06:29 Netty using native Epoll event loop
INFO  20:06:29 Using Netty Version: [netty-buffer=netty-buffer-4.0.23.Final.208198c, netty-codec=netty-codec-4.0.23.Final.208198c, netty-codec-http=netty-codec-http-4.0.23.Final.208198c, netty-codec-socks=netty-codec-socks-4.0.23.Final.208198c, netty-common=netty-common-4.0.23.Final.208198c, netty-handler=netty-handler-4.0.23.Final.208198c, netty-transport=netty-transport-4.0.23.Final.208198c, netty-transport-rxtx=netty-transport-rxtx-4.0.23.Final.208198c, netty-transport-sctp=netty-transport-sctp-4.0.23.Final.208198c, netty-transport-udt=netty-transport-udt-4.0.23.Final.208198c]
INFO  20:06:29 Starting listening for CQL clients on /0.0.0.0:9042...
INFO  20:06:29 Binding thrift service to /0.0.0.0:9160
INFO  20:06:29 Listening for thrift clients...
</code></pre>

And here's the last bit of log from the node that I did NOT restart:

<pre><code>
4392bcdd35a684174e047860b377/system-local-ka-4-Data.db'), SSTableReader(path='/var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-1-Data.db'), SSTableReader(path='/var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-2-Data.db'), SSTableReader(path='/var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-3-Data.db')]
INFO  20:05:13 Node /172.30.0.35 state jump to normal
INFO  20:05:13 Waiting for gossip to settle before accepting client requests...
INFO  20:05:13 Compacted 4 sstables to [/var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-5,].  5,885 bytes to 5,721 (~97% of original) in 129ms = 0.042294MB/s.  4 total partitions merged to 1.  Partition merge counts were {4:1, }
INFO  20:05:19 OutboundTcpConnection using coalescing strategy DISABLED
INFO  20:05:20 Handshaking version with /172.30.1.116
INFO  20:05:20 Node /172.30.1.116 is now part of the cluster
INFO  20:05:20 InetAddress /172.30.1.116 is now UP
WARN  20:05:20 Not marking nodes down due to local pause of 9701751803 > 5000000000
INFO  20:05:21 No gossip backlog; proceeding
INFO  20:05:21 Netty using native Epoll event loop
INFO  20:05:21 Using Netty Version: [netty-buffer=netty-buffer-4.0.23.Final.208198c, netty-codec=netty-codec-4.0.23.Final.208198c, netty-codec-http=netty-codec-http-4.0.23.Final.208198c, netty-codec-socks=netty-codec-socks-4.0.23.Final.208198c, netty-common=netty-common-4.0.23.Final.208198c, netty-handler=netty-handler-4.0.23.Final.208198c, netty-transport=netty-transport-4.0.23.Final.208198c, netty-transport-rxtx=netty-transport-rxtx-4.0.23.Final.208198c, netty-transport-sctp=netty-transport-sctp-4.0.23.Final.208198c, netty-transport-udt=netty-transport-udt-4.0.23.Final.208198c]
INFO  20:05:21 Starting listening for CQL clients on /0.0.0.0:9042...
INFO  20:05:21 Binding thrift service to /0.0.0.0:9160
INFO  20:05:21 Listening for thrift clients...
INFO  20:06:13 InetAddress /172.30.1.116 is now DOWN
INFO  20:06:13 Handshaking version with /172.30.1.116
INFO  20:06:21 Handshaking version with /172.30.1.116
INFO  20:06:21 Node /172.30.1.116 has restarted, now UP
INFO  20:06:21 InetAddress /172.30.1.116 is now UP
INFO  20:06:21 InetAddress /172.30.1.116 is now UP
INFO  20:06:21 InetAddress /172.30.1.116 is now UP
INFO  20:06:21 InetAddress /172.30.1.116 is now UP
INFO  20:06:21 Node /172.30.1.116 state jump to normal

</code></pre>

Any idea what the problem is?

**Comment by tashburn** [comment]
Update --

Turns out the nodes *do* actually reconnect. It just took a while -- somewhere between 15-45 minutes.

Is there a way to make the reconnect much faster? I expect it to be immediate.

**Comment by yosifkit** [comment]
Were you able to get them to reconnect any faster?

**Comment by tashburn** [comment]
No, wasn't.

**Comment by yosifkit** [comment]
I just tried a two node setup and it seemed to be pretty quick (cassandra 2.2 or 3.0); sometimes it would sleep for 30 seconds before syncing.  So I am not sure what the problem is :confused:.

```console
$ docker run --name cass1 cassandra
$ docker run --name cass2 --link cass1:cassandra cassandra
$ # --link just fills in "seeds"
$ # wait for gossip to finish
$ docker exec -it cass1 nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.6  32.52 KB   256          ?       4cfec480-08e8-453d-911d-aa7778bf360d  rack
1
UN  172.17.0.5  96.94 KB   256          ?       b122dac1-b546-4a12-9819-6120df6c3d5b  rack
1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
$ docker stop cass2
$ docker exec -it cass1 nodetool status
DN  172.17.0.6  113.21 KB  256          ?       4cfec480-08e8-453d-911d-aa7778bf360d  rack
$ docker start cass2
$ docker exec -it cass1 nodetool status
UN  172.17.0.6  208.58 KB  256          ?       4cfec480-08e8-453d-911d-aa7778bf360d  rack
```

**Comment by tashburn** [comment]
I think it was that 30s sync that I was experiencing.

**Comment by tianon** [comment]
This _sounds_ like it's probably not anything specific to the Dockerization, and is either something inherent to Cassandra itself or its default configuration.  I'm going to close for now, but if we can find something more conclusively pointing to an issue with the image and not Cassandra itself, having a new issue filed with details (or a PR with a fix) would be grand!  Thanks!
