### ISSUE TITLE
Can only run two container

### ISSUE THREAD

**Issue by EasonWang01** [docker-library/cassandra#114]
Hi,if I run third container it will stop the oldest one and keep it two docker ps of cassandra container,
how to change it?Thanks.

**Comment by tianon** [comment]
Do you have enough RAM to run three copies of `cassandra`?  By default, it probably uses something like 40-50% of available RAM, so it's honestly surprising you managed to get two running side-by-side, let alone three.

You'll probably want to play with the `MAX_HEAP_SIZE` and `HEAP_NEWSIZE` environment variables to control Cassandra's memory usage.  See http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsTuneJVM.html for more information.
