### ISSUE TITLE
Expose further settings in Cassandra image

### ISSUE THREAD

**Issue by sunnychanwork** [docker-library/cassandra#121]
We would like to expose these configuration settings which has been useful in our production environment

storage_port 
ssl_storage_port 
native_transport_port 
rpc_port 
read_request_timeout_in_ms 
request_timeout_in_ms 
range_request_timeout_in_ms 
write_request_timeout_in_ms 
counter_write_request_timeout_in_ms

**Comment by tianon** [comment]
No, see https://github.com/docker-library/cassandra/pull/41, https://github.com/docker-library/cassandra/pull/112
