### ISSUE TITLE
Cassandra Port does not running

### ISSUE THREAD

**Issue by vovkanaz** [docker-library/cassandra#127]
Cassandra Port 9160 does not running:
Inside conainer:
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:7199            0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:9042            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:37173         0.0.0.0:*               LISTEN      -               
tcp        0      0 10.244.1.125:7000       0.0.0.0:*               LISTEN      -    
But 9160 does not exists.
I am look in Dockerfile, and looks like all very good
-------------------------------------------------------
EXPOSE 7000 7001 7199 9042 9160
Inside cassandra config all looks fine too:
-------------------------------------------------------
listen for clients on rpc_port: 9160
We are using Cassandra in Kubernetes
This is a part of Deployment:
containers:
        - name: cassandra
          image: cassandra:latest
          ports:
          - containerPort: 7000
          - containerPort: 7001
          - containerPort: 9042
          - containerPort: 9160
other ports working good.
What can you advice. Thanks!

**Comment by tianon** [comment]
`EXPOSE` in the `Dockerfile` is simply metadata -- it serves no purpose beyond noting to users and orchestration systems which ports this image will likely provide/use (it does not get passed to Cassandra itself in any way).

Port 9160 is for Cassandra's Thrift API server, which is disabled by default -- I was able to get it to start by using `docker exec` into my running container and invoking `nodetool enablethrift`.  I'm sure there are other ways to enable it as well.
