### ISSUE TITLE
Only two node works

### ISSUE THREAD

**Issue by gaborpeltzer** [docker-library/cassandra#128]
Hi!

I try start cluster with three nodes in one machine. If started the third node, then one go down. Always two node is up.

Start first node:
docker run --name c1 -d -p 9042:9042 -e CASSANDRA_BROADCAST_ADDRESS=172.17.0.2 -e CASSANDRA_LISTEN_ADDRESS=172.17.0.2 -e CASSANDRA_RPC_ADDRESS=172.17.0.2 -e CASSANDRA_SEEDS=172.17.0.2,172.17.0.3,172.17.0.4 cassandra:latest

Start second node:
docker run --name c2 -d -e CASSANDRA_BROADCAST_ADDRESS=172.17.0.3 -e CASSANDRA_LISTEN_ADDRESS=172.17.0.3 -e CASSANDRA_RPC_ADDRESS=172.17.0.3 -e CASSANDRA_SEEDS=172.17.0.2,172.17.0.3,172.17.0.4 cassandra:latest

Start third node:
docker run --name c3 -d -e CASSANDRA_BROADCAST_ADDRESS=172.17.0.4 -e CASSANDRA_LISTEN_ADDRESS=172.17.0.4 -e CASSANDRA_RPC_ADDRESS=172.17.0.4 -e CASSANDRA_SEEDS=172.17.0.2,172.17.0.3,172.17.0.4 cassandra:latest
(after first go down)

If manually start the first, then another go down. Is there anybody's got to know, why?

**Comment by tianon** [comment]
If these are all on the same host, your issue is undoubtedly memory
related.  By default, an instance of Cassandra will use a percentage of ALL
available memory, so to make this work, you'll need to adjust that
configuration.

**Comment by gaborpeltzer** [comment]
Works with three VMs. Thanks!
