### ISSUE TITLE
Java VM version : OpenJDK -> Oracle

### ISSUE THREAD

**Issue by blop** [docker-library/cassandra#13]
Hello,

When starting your docker image, I get those warning in my logs : 

INFO  [main] 2015-06-25 14:37:18,967 CassandraDaemon.java:168 - JVM vendor/version: OpenJDK 64-Bit Server VM/1.7.0_79
WARN  [main] 2015-06-25 14:37:18,968 CassandraDaemon.java:173 - OpenJDK is not recommended. Please upgrade to the newest Oracle Java release

It seems a bit strange to provide an "official" cassandra image that uses a "not recommended" JVM version.

I suggest you switch to the latest Oracle 1.8 JVM.

**Comment by yosifkit** [comment]
As far as I interpret the [Oracle Java licensing](http://www.oracle.com/technetwork/java/javase/terms/license/index.html), we can bundle in Oracle Java in order to run other software, but I am not a lawyer and we would need to ensure that we don't break the license or get stuck with onerous liabilities or fees.

**Comment by blop** [comment]
I understand. It's also explained on : 
https://registry.hub.docker.com/_/java/

I guess we can at least upgrade to Java 8 then. ;-)
And/or provide a how to switch to Oracle version manually maybe.

Also, see http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

**Comment by yosifkit** [comment]
For switching to Java 8, that would have to be upstream since we just use the apt repo provided by apache.org which has `openjdk-7-jre-headless | java7-runtime` in its `Depends`.

**Comment by blop** [comment]
Or we could use the official Oracle JDK base image that now exists : 
https://github.com/oracle/docker-images/tree/master/OpenJDK

But it might cause other issues (yum based).

**Comment by johntmyers** [comment]
Is there any update on this? Other solutions like DSE seem to be using Oracle JDK base images as well i.e. (`FROM nimmis/java:oracle-8-jdk`)

**Comment by z0mb1ek** [comment]
is it not what you need https://store.docker.com/images/oracle-serverjre-8 ?

**Comment by tianon** [comment]
@z0mb1ek yes, that is what a user would need to build their own image of Cassandra on the Oracle JDK.  We cannot use that both because it is not part of the [Official Images program](https://github.com/docker-library/official-images), and because it requires a license to download/use/distribute.

**Comment by blop** [comment]
I guess a better solution would be that Cassandra fully support the OpenJDK and drops any requirement or recommandation for the Oracle JDK.

It's already working with the OpenJDK anyway, which is more open source friendly.

**Comment by blop** [comment]
Actually they already did ;-)
https://github.com/apache/cassandra/commit/194bad22f71da3007a7f9ab5561d6f211d140c45#diff-abd487d32d1695bdb1a05c5247453429L185

http://cassandra.apache.org/doc/latest/getting_started/installing.html#prerequisites also confirms OpenJDK can be used.

I'm closing this issue as it's became irrelevant.
