### ISSUE TITLE
There is no 'ip' tool in newly created image 3.11

### ISSUE THREAD

**Issue by Andrey-mp** [docker-library/cassandra#134]
We used this tool inside the cassandra's container to configure it. With last changes this tool is not available.

**Comment by yosifkit** [comment]
I would guess this is caused by the move to debian stretch: https://github.com/docker-library/cassandra/pull/133.

**Comment by tianon** [comment]
Since Cassandra has such a strong fetish for IPs, this is probably an important tool for us to add back.  I'll make a PR.
