### ISSUE TITLE
How to pass environment variable in docker container?

### ISSUE THREAD

**Issue by junaidrazzaq323** [docker-library/cassandra#141]
I am using cassandra:3.11 docker image and I want to pass the following property in cassandra.yaml as environment variable:

- `write_request_timeout_in_ms`

This environment variable is not mentioned in [https://hub.docker.com/_/cassandra/](url)
I am assuming that prepending `CASSANDRA_` would work.

So, I am running the container using:
`docker run -it --name casb-cassandra -e CASSANDRA_WRITE_REQUEST_TIMEOUT_IN_MS=20000 cassandra-test:0.1`

Then I exec into the container and inside `/etc/cassandra/cassandra.yaml`, `write_request_timeout_in_ms` is not set.

**Comment by yosifkit** [comment]
If it is not mentioned in the docs (or in the [docker-entrypoint.sh](https://github.com/docker-library/cassandra/blob/master/docker-entrypoint.sh)) then it is not a supported environment variable. We only support a minimal set of configuration values for items that change per container when setting up a cluster.  Any other configuration would need to be provided by supplying your own `cassandra.yaml`.

**Comment by junaidrazzaq323** [comment]
How can I supply my own `cassandra.yaml` file?

**Comment by yosifkit** [comment]
Either build an image with it in the proper path (`/etc/cassandra/`):

```Dockerfile
FROM cassandra:3.11
COPY cassandra.yaml /etc/cassandra/
```
Or mount one at run time with `-v` on`docker run`:
```console
$ docker run -d -v /path/to/configs/:/etc/cassandra/ cassandra:3.11
```
