### ISSUE TITLE
failed to build cassandra docker image

### ISSUE THREAD

**Issue by shufanhao** [docker-library/cassandra#145]
Want to change value of read_request_timeout_in_ms and write_request_timeout_in_ms in cassandra.yaml by add sed commands in docker-entrypoint.sh for 3.11 version in my laptop Mac, but failed, error as belows 

2018-04-17 03:19:32 (897 KB/s) - '/usr/local/bin/gosu.asc' saved [543/543]

+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.Vo7oxvy7NQ
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keybox '/tmp/tmp.Vo7oxvy7NQ/pubring.kbx' created
g**pg: keyserver receive failed: Cannot assign requested address**
The command '/bin/sh -c set -x 	&& apt-get update && apt-get install -y --no-install-recommends ca-certificates wget && rm -rf /var/lib/apt/lists/* 	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" 	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" 	&& export GNUPGHOME="$(mktemp -d)" 	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu 	&& rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc 	&& chmod +x /usr/local/bin/gosu 	&& gosu nobody true 	&& apt-get purge -y --auto-remove ca-certificates wget' returned a non-zero code: 2

**Comment by shufanhao** [comment]
Thanks Yosifkit.

**Comment by Avik1993** [comment]
@yosifkit Just one question on this.
Will copy local docker-entrypoint.sh to /usr/local/bin overwrite the existing one along with sym link created.
Also, do we need to add 
`CMD ["cassandra","-f"]` at last?

Thanks for help
