### ISSUE TITLE
Cassandra Querying from a webapp gives error "java.lang.IllegalArgumentException: replicate_on_write is not a column defined in this metadata"

### ISSUE THREAD

**Issue by SaifKazi123** [docker-library/cassandra#15]
I have taken the latest cassandra official, running a container through it. I am trying to connect the cassandra to my webapp, the connection is happening but when I do GET api call returning cassandra data, it gives the following error: 

java.lang.IllegalArgumentException: replicate_on_write is not a column defined in this metadata

**Comment by yosifkit** [comment]
Is that possibly related to https://issues.apache.org/jira/browse/CASSANDRA-6631?

**Comment by yosifkit** [comment]
Closing old issue.  Feel free to message back if you would like to keep this open.
