### ISSUE TITLE
Error after starting cassandra

### ISSUE THREAD

**Issue by cirix** [docker-library/cassandra#154]
Hi guys,
I am starting cassandra: docker run -d cassandra:latest and the logs state

> standard_init_linux.go:190: exec user process caused "no such file or directory"

Even though most people say is related to  CRLF characters I pulled everything, but still my container for cassandra fails to start.  Also I don't know if related by the WorkingDir after I docker inspect the container is an empty string, where if I follow the standard_init_linux.go on the line that it fails, that things looks like a perfect candidate.All the other containers are working fine.

kind regards
Nick

**Comment by tianon** [comment]
This error message usually means one of a few things.  The most common causes are a bad shebang line (for example, trying to run a bash script in Alpine without having bash installed) or missing shared libraries.

Given that you pulled the image (not built locally), it's probably _more_ likely you've got a corrupted image.  Have you tried fully purging all the image layers and re-pulling?  I can't reproduce:

```console
$ docker pull cassandra:latest
latest: Pulling from library/cassandra
be8881be8156: Already exists 
fb2c677ef354: Pull complete 
bba7d7818fb8: Pull complete 
233a12098077: Pull complete 
3446f702d0d1: Pull complete 
2e3b739ed5d5: Pull complete 
6d104fb5620d: Pull complete 
458446f55982: Pull complete 
9d44379168d2: Pull complete 
e191856325d3: Pull complete 
Digest: sha256:17205a96d799a09d91a47b49b4bf98f3f28992f44077d5e6edab829e4655ef02
Status: Downloaded newer image for cassandra:latest

$ docker run -d --name test cassandra:latest
3d7334157c739e087b7af8215b3273bf079d5906f0dd46072fed811ed31e5c83

$ docker logs --tail=3 test
INFO  [main] 2018-08-20 22:14:29,880 Server.java:156 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...
INFO  [main] 2018-08-20 22:14:29,898 CassandraDaemon.java:529 - Not starting RPC server as requested. Use JMX (StorageService->startRPCServer()) or nodetool (enablethrift) to start it
INFO  [OptionalTasks:1] 2018-08-20 22:14:31,848 CassandraRoleManager.java:356 - Created default superuser role 'cassandra'
```

**Comment by wglambert** [comment]
Since there isn't anything denoting an error with the image and the issue isn't reproducible I'm going to close.
