### ISSUE TITLE
Install multi DC cassandra on two separate Openshift Origin clusters to get HA and DR

### ISSUE THREAD

**Issue by Natarajan77** [docker-library/cassandra#157]
We are in the process of installing Cassandra as multi DC on Openshift origin and running into challenges.

So we have two openshift clusters which are separated by Datacenter

Openshift Origin AB hosted in datacenter ELC

Openshift Origin CD hosted in datacenter CLC

Going to install cassandra cluster on AB and CD. Both cassandra cluster on AB and CD should be able to talk with each other. So that we get HA and DR.

Current challenge cassandra cluster in AB and CD they are not able to talk with each other.

Cassandra broadcasts on pod ip and unfortunately pod ips are accessible only in local origin cluster not across remote. How to make the pod ip accessible across open shift origin clusters?

**Comment by tianon** [comment]
I'm sorry, but this really isn't a support forum.  It sounds like what you need is help from folks who are familiar with OpenShift and how to configure the networking, so I'd recommend trying to find an OpenShift-specific community in which to raise your question.
