### ISSUE TITLE
Nodetool responding with "SocketTimeoutException: 'Read timed out'" with remote cassndra

### ISSUE THREAD

**Issue by venkat-koppisetti** [docker-library/cassandra#159]
running nodetool and cassandra DB in two different containers and was trying to get the status of cassabdra DB using nodetool from another container using below menioned command, getting SocketTimeoutException: 'Read timed out'" with remote cassndra

nodetool -h 172.17.0.6 -p 9042 status

**Comment by tianon** [comment]
Looks like you need to set `-e LOCAL_JMX=no` on your container (with the default `cassandra-env.sh` contents) in order to have JMX listen outside the container:

https://github.com/apache/cassandra/blob/42c92b9768b58884e426490e103583b82e892d4e/conf/cassandra-env.sh#L215-L245

**Comment by venkat-koppisetti** [comment]
My cassandra DB container is listening on 9042 port.
**I tried with following options set in cassandra.yaml:**
rpc_address: localhost to container-ip
rpc_port: 9160 to 9042
read_request_timeout_in_ms: 5000 to 60000

**I tried with following options set in cassandra-env.sh:**
JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=<public name>" to Host-IP/ container-ip.
JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=true" to false
JMX_PORT="7199" to 9042
LOCAL_JMX=no

and using "**nodetool -h 172.17.0.7  -p 9042 status**" command to get the status of remote cassandra.
**But getting following output:**
nodetool: Failed to connect to '172.17.0.7:9042' - SocketTimeoutException: 'Read timed out'.
