### ISSUE TITLE
Do we need chown of config files in docker-entrypoint.sh ?

### ISSUE THREAD

**Issue by maver1ck** [docker-library/cassandra#165]
I have following problem.
I want to use this image on kubernetes and replace some of the config files by mounting configmap.
The problem is that docker-entrypoint.sh is trying to change ownership of files in $CASSANDRA_CONFIG and Kubernetes is mounting configmap read-only.

So the question is:
Do we need chown of config files in docker-entrypoint.sh ?
Maybe it's enough to change /var/lib/cassandra and /var/log/cassandra ?

**Comment by tianon** [comment]
Sounds like you probably want to overwrite entrypoint entirely and just run
"cassandra -f" directly (since you likely don't want any of the behavior of
the default entrypoint script if you're mounting a read-only configuration
file).

**Comment by maver1ck** [comment]
Sounds like idea.
I will test it tomorrow. Thanks

**Comment by maver1ck** [comment]
OK. I needed to create custom bash script for the entrypoint but it worked.
