### ISSUE TITLE
Docker's Official Images Build is broken on ARMv8 (AAarch64)

### ISSUE THREAD

**Issue by lag-linaro** [docker-library/cassandra#167]
See [Docker's Official Images Build Server](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/cassandra/) for details.

Jessie is at end-of-life and should no longer be used as a base for projects.

Essentially, this project should migrate from Debian Jessie to Debian Stretch at your earliest convenience.

**Comment by yosifkit** [comment]
Closed by https://github.com/docker-library/cassandra/pull/166

**Comment by lag-linaro** [comment]
Thanks for addressing this.

Could you activate a re-build of the [Official Images Build](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/cassandra/) please?

**Comment by yosifkit** [comment]
They'll be built once https://github.com/docker-library/official-images/pull/5020 merges.
