### ISSUE TITLE
"The stack size specified is too small, Specify at least 328k" for aarch64 

### ISSUE THREAD

**Issue by ZiluTian** [docker-library/cassandra#174]
Hello, 
I get the same error as described here but for aarch64: https://issues.apache.org/jira/browse/CASSANDRA-13345

Currently the modification of the stack size is done by checking if the architecture is ppc64le. Can you please include aarch64 as well? 

Thanks

**Comment by wglambert** [comment]
This repo is for the Docker official-image of Cassandra. Are you wanting to ask the Apache foundation, such as the jira bug tracker you linked to?

**Comment by tianon** [comment]
Are you referring to this block?

https://github.com/docker-library/cassandra/blob/197a99a985c50eefcf71ad6189764e7e81934596/Dockerfile.template#L126-L147

**Comment by tianon** [comment]
(I'm not able to reproduce any issues here -- I can run `cassandra:latest` on `arm64` just fine as-is without any modifications. :confused:)

**Comment by ZiluTian** [comment]
Hi, 
Thanks for getting back to me. I have attached my server config, docker version below, and a screenshot below. The server existed immediately and the content of the trace complains about the stack size. I suspect that it is related to the code snippet you have pointed at, but it is only a speculation. If you have any other suggestion, let me know. Thanks!  

Server config: 

NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Docker version: 
Docker version 18.09.0, build 4d60db4

<img width="1061" alt="screen shot 2019-01-15 at 09 37 44" src="https://user-images.githubusercontent.com/28329737/51168654-2b365a00-18aa-11e9-893f-91020c605e8f.png">

**Comment by tianon** [comment]
Have you pulled the latest image version?  Does your device have enough
memory to run Cassandra?

**Comment by ZiluTian** [comment]
Yes to both

**Comment by tianon** [comment]
Well, we can't reproduce the failure, so any other information that might
help us do so is going to be crucial to us creating and verifying a fix. 😅

**Comment by ZiluTian** [comment]
Hi, I recently brought it up on qemu (aarch64) Ubuntu 16.04.2 LTS, and there was no such issue. Maybe it is due to the OS rather than aarch64.
