### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by HCHCHH** [docker-library/cassandra#177]
Thanks for providing this useful container! I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
does not recommend to enable them in production but the default is enabled:

![image](https://user-images.githubusercontent.com/4555674/56547979-b8392100-6533-11e9-9347-aafdfaef4721.png)

Shall we disable them?
Thanks!

**Comment by tianon** [comment]
The configuration included in this image is the vanilla configuration file provided by upstream's own Debian packages -- at most, we have an entrypoint script which can modify a few values based on changes in the environment such as IP addresses (which has frankly been a massive source of annoyance and bugs and we'd be thrilled to remove it if we reasonably could).

I would recommend taking this up with Cassandra upstream regarding the default configuration of the packages they publish under http://www.apache.org/dist/cassandra/debian.
