### ISSUE TITLE
Old version does not work

### ISSUE THREAD

**Issue by fbeneventi** [docker-library/cassandra#178]
Building version v3.0.17 does not work anymore:

`+ apt-get install -y cassandra=3.0.17 cassandra-tools=3.0.17
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '3.0.17' for 'cassandra' was not found
E: Version '3.0.17' for 'cassandra-tools' was not found
`

This may be related:

https://www.mail-archive.com/user@cassandra.apache.org/msg58790.html

**Comment by wglambert** [comment]
Does doing a `FROM cassandra:3.0.17` work for the changes you want to make? Currently we only support 3.0.18 

You can use the image hash to pull it and then re-tag it to `cassandra:3.0.17`
https://github.com/docker-library/repo-info/blob/b1095f08b343790d0b9a176ff94ace4efd471533/repos/cassandra/remote/3.0.17.md

```console
$ docker pull cassandra@sha256:45a00293d46d31319f4d4bcebc23c7916453f9054186db2b38d8c3f52bce5e06
sha256:45a00293d46d31319f4d4bcebc23c7916453f9054186db2b38d8c3f52bce5e06: Pulling from library/cassandra
Digest: sha256:45a00293d46d31319f4d4bcebc23c7916453f9054186db2b38d8c3f52bce5e06
Status: Image is up to date for cassandra@sha256:45a00293d46d31319f4d4bcebc23c7916453f9054186db2b38d8c3f52bce5e06

$ docker tag cassandra@sha256:45a00293d46d31319f4d4bcebc23c7916453f9054186db2b38d8c3f52bce5e06 cassandra:3.0.17
```

**Comment by fbeneventi** [comment]
Thanks, the FROM approach worked.
