### ISSUE TITLE
What is the default superuser credential for this container?

### ISSUE THREAD

**Issue by timjkiddCTL** [docker-library/cassandra#181]
What is the default superuser credential for this container?

After deployment, I've tried logging into cqlsh using '-u cassandra -p cassandra' (which appears successful), then have tried creating a new superuser - and I receive this message:

Unauthorized: Error from server: code=2100 [Unauthorized] message="Only superusers can create a role with superuser status"

Is 'cassandra/cassandra' not the default superuser with this container?

Thanks!

**Comment by wglambert** [comment]
Cassandra needs authentication enabled to be able to edit/create superusers. You'll want to create a cassandra.yaml with credentials setup and mount it in the container https://github.com/docker-library/docs/tree/master/cassandra#configuring-cassandra

This image doesn't have any authentication by default so any user/password will work, even none at all
