### ISSUE TITLE
Maybe install ntp?

### ISSUE THREAD

**Issue by moldcraft** [docker-library/cassandra#19]
I checked `sudo docker exec -it cassandra bash` -> `top` and there is no `ntp` running.

https://blog.logentries.com/2014/03/synchronizing-clocks-in-a-cassandra-cluster-pt-1-the-problem/

**Comment by yosifkit** [comment]
No need for that, time is tracked on the host kernel (and containers all use the host kernel).
> The clock of the container is the same as the clock of the host ([stackoverflow](https://stackoverflow.com/questions/22800624/will-docker-container-auto-sync-time-with-the-host-machine#comment34898836_22820278))
