### ISSUE TITLE
 Can you add a configurable cassandra password in version office docker image 3.11.5? 

### ISSUE THREAD

**Issue by binbinshi** [docker-library/cassandra#198]
Hope to configure cassandra's default password information through env. When we use authenticator: PasswordAuthenticator as the access security restriction, the image version is the official 3.11.5 。

 don't tell me use the cqlsh to update the passwrd after the cassandra service is start up

 anyone give me some advice？ 

 thanks

**Comment by wglambert** [comment]
Cassandra needs authentication enabled to be able to edit/create superusers. You'll want to create a `cassandra.yaml` with provided credentials and mount it in the container https://github.com/docker-library/docs/tree/master/cassandra#configuring-cassandra

This image doesn't have any authentication by default
