### ISSUE TITLE
Unable to start latest cassandra.

### ISSUE THREAD

**Issue by manojvai** [docker-library/cassandra#204]
I am able to run cassandra:3.0.18 on openshift without any issue but with the latest version (3.11.6), it throws below error:

Running Cassandra as root user or group is not recommended - please start Cassandra using a different system user.
--
  | If you really want to force running Cassandra as root, use -R command line option.

How to go around this issue?

**Comment by yosifkit** [comment]
>   | If you really want to force running Cassandra as root, use -R command line option.

So pass `-R` to the command:
```console
$ docker run --name some-cassandra -it --rm --user cassandra:0 cassandra:3.11.6 -R
```
