### ISSUE TITLE
High CPU utilization even when the cluster is idle

### ISSUE THREAD

**Issue by yogeshbidari** [docker-library/cassandra#209]
**Description**

We have 3 node cassandra cluster on kubernetes.
The CPU utilization of the cluster/pods is high even when there is no load or queries running on the cluster. We are using bitnami/cassandra:3.11.3 docker image.
We are using grafana for monitoring the load.

**Version**

cassandra version: 3.11.3
GKE version 1.14.10

 
 **Infrastructure**

Using GCP GKE for the k8s cluster deployment.

Assigned resource request and limits
Requests:
- cpu: 3
- memory: 15GB
Limits:
- cpu: 6
- memory: 30GB

**Comment by wglambert** [comment]
>We are using bitnami/cassandra:3.11.3 docker image.

You should ask over at https://github.com/bitnami/bitnami-docker-cassandra

This repo is for https://hub.docker.com/_/cassandra
