### ISSUE TITLE
libjemalloc 3.6 causes segment fault on ARM64 platform

### ISSUE THREAD

**Issue by fgggid** [docker-library/cassandra#211]
I've tried the 3.11.6 docker on my ARM64 server. It crashes constantly.
If I purge libjemalloc1, cassandra can run.
If I upgrade to libjemalloc2(version is 5.1.0) from debian buster, and make proper symbolic link, cassandra can run too.

related commit:
https://github.com/jemalloc/jemalloc/commit/7a8bc7172b17e219b3603e99c8da44efb283e652

**Comment by yosifkit** [comment]
I'd be careful installing a Debian Buster package on these Ubuntu Bionic (18.04) based images.

Unfortunately the `libjemalloc2` package is only available on `eoan` (19.10) or newer. The images are based on `adoptopenjdk:8-jre-hotspot-bionic` and they don't yet have a `focal` (20.04) variant (https://github.com/AdoptOpenJDK/openjdk-docker/issues/354).
