### ISSUE TITLE
No new images for 2.2 created since 2.2.16

### ISSUE THREAD

**Issue by elsmorian** [docker-library/cassandra#215]
2.2.16 is the latest Docker image available however we are now up to .18 in that release - https://github.com/apache/cassandra/blob/cassandra-2.2/CHANGES.txt

**Comment by tianon** [comment]
Indeed, that would be due to https://issues.apache.org/jira/browse/CASSANDRA-16008 😞

**Comment by elsmorian** [comment]
I flagged this in the Cassandra Slack channel and hopefully this will be pushed through shortly!

**Comment by tianon** [comment]
Apparently fixed! https://github.com/docker-library/cassandra/commit/cb366dd :tada:
(https://github.com/apache/cassandra/pull/757 somehow led to https://github.com/apache/cassandra/commit/ed8005552376188abb81894fb8c9c611ebd6379a, so probably can be closed?)
