### ISSUE TITLE
Give executable permissions to `docker-entrypoint.sh` 

### ISSUE THREAD

**Issue by fincardona** [docker-library/cassandra#220]
Hello!

I tried to spin up the Cassandra container within a docker network, but I got the following error 
```
"docker-entrypoint.sh": executable file not found in $PATH: unknown
```
that I solved by adding:  
```
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
```
at line 155 of Dockerfile.

I think it could be useful to add this command to the code.

Thanks.

**Comment by wglambert** [comment]
Did you build your own image? 
I can't reproduce
```console
$ docker run -d --rm --name cassandra cassandra
d001e41d53a692a80099e7a27b98111325212e97cf6ae316af56e23d9875c790

$ docker exec -it cassandra bash
root@d001e41d53a6:/# ls -l /usr/local/bin
total 2352
-rwxrwxr-x 1 root root    2241 Nov 26 03:12 docker-entrypoint.sh
-rwxr-xr-x 1 root root 2404352 Apr 16  2020 gosu
```

**Comment by yosifkit** [comment]
You are welcome to build your own images from the Dockerfile + context, but the images are provided on Docker Hub: http://hub.docker.com/_/cassandra.

Same basic issue as https://github.com/docker-library/postgres/issues/386#issuecomment-350323371. TL;DR: The execute permissions are already tracked in git, there should be no need to apply it manually unless you didn't use git to download the files.
