### ISSUE TITLE
Publish Cassandra latest 3.x images for linux/arm64 platform

### ISSUE THREAD

**Issue by emerkle826** [docker-library/cassandra#222]
Looking at the tags available [here](https://hub.docker.com/_/cassandra?tab=tags), I see that Cassandra 3.11.10 was published for linux/amd64, but I don't see the linux/arm64 image. The same for Cassandra 3.0.24. Could these new releases be published for linux/arm64 like the previous 3.11.9 and 3.0.23 images?

**Comment by yosifkit** [comment]
Just as soon as the `adoptopenjdk:8-jre-hotspot-focal` has them again, we will. https://github.com/docker-library/official-images/pull/9490#issuecomment-767010171

**Comment by sw-yx** [comment]
swinging by to add search terms for those people who ran into this (i'm not a docker pro... spent 2 hours trying to figure this out today):

this issue manifests when you run cassandra 3.11 inside docker on an apple silicon M1 mac (ARM processor) and it finds 3.11.10 without an ARM build. this leads you to a `“no matching manifest for linux/arm64/v8 in the manifest list entries”` error. the resolution (for now) is to pin version to 3.11.9 and it'll resume working.

**Comment by christian-toscano** [comment]
@sw-yx thank you man, definitely saved my day!
I can confirm cassandra 3.11.9 works on Mac with M1 processor

**Comment by emerkle826** [comment]
Closing this as it seems ARM builds are being published again (for 3.11.10 and the latest 4.0-rc1):
https://hub.docker.com/_/cassandra?tab=tags&page=1&ordering=last_updated
