### ISSUE TITLE
Configurable user uid for cassandra

### ISSUE THREAD

**Issue by iosonogio** [docker-library/cassandra#227]
The cassandra image is prepared with a user 'cassandra' having uid 999.

If the container is run on hosts without usernamespaces this can be problematic (at least messy) since another user with the same id may already exist on the host (like it happens on Centos/RedHat).

How about having a configurable user via an environment variable to set at build time?

**Comment by tianon** [comment]
Good catch!  The ability to run as an arbitrary user was originally implemented in https://github.com/docker-library/cassandra/pull/48, but at some point along the way we started overwriting the configuration file even when it hasn't changed which unintentionally breaks that.  I've filed #228 with a fix. :smile:

**Comment by tianon** [comment]
Bit of a false start, but fixed in https://github.com/docker-library/cassandra/pull/229 :crossed_fingers:

**Comment by iosonogio** [comment]
Hey, that's great, thank you so much! Please make it available for both versions 4 and 3 (I'm currently using 3.11 which I guess it's the main stable version)

**Comment by iosonogio** [comment]
Sorry, I just saw that you implemented the fix for every version of cassandra! WOW
Question: I see that uid 999 is still set fixed in the Dockerfile,  will it suffice to run the container with the --user option to have cassandra run with a different user?

**Comment by yosifkit** [comment]
> will it suffice to run the container with the --user option to have cassandra run with a different user?

Yes! (and, similarly, [`user:`](https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir) in docker-compose.yml, etc)
