### ISSUE TITLE
4 nodes Cassandra cluster on 2 servers

### ISSUE THREAD

**Issue by moonsyim** [docker-library/cassandra#23]
Hello

seriously I'd like to make 4 nodes Cassandra cluster on 2 servers like

1st Server : Container A, Container B

2st Server : Container C, Container D

Container A, Container C are seed node.

I'd like to make

Container A is linked (bridge) to 1st host eth0

Container B is linked (bridge) to 1st host eth1

Container C is linked (bridge) to 2nd host eth0

Container D is linked (bridge) to 2nd host eth1

but it looks like

Container A, B links to 1st node's eth0 all.

Container C, D links to 2nd node's eth0 all.

–net=host is not good option to me.

Do you have any good suggestion for 4 nodes (4 container) Cassandra cluster on 2 servers ?

**Comment by yosifkit** [comment]
I think just starting the containers with the address of the interface that you want it available should work; in other words, if eth0 on the first host is 10.42.42.42, then run with `-p 10.42.42.42:7000:7000 -e CASSANDRA_BROADCAST_ADDRESS=10.42.42.42`.  I am not sure if you'll also need to map the rest of the [defined ports](https://github.com/docker-library/cassandra/blob/db8d7126b27016f3f990c14abe0d9f4c3ce00179/Dockerfile.template#L25-L30).  On all but the first you'll probably need to run with  `-e CASSANDRA_SEEDS=10.42.42.42`.

**Comment by yosifkit** [comment]
Closing old issue that looks fixed
