### ISSUE TITLE
Apple m1 build for version 2.0.14

### ISSUE THREAD

**Issue by crispinkoech** [docker-library/cassandra#232]
Hey, if it's not too much of a bother, could you guys build `v2.014` for the new Apple Silicon chip? I know it's an extremely old version, but we have it some of our older systems and would prefer to keep my local environment still similar to that one. I'd be willing to build it myself if you could me to some documentation on how I'd go around doing so.

**Comment by tianon** [comment]
Unfortunately, this is not something we'll do directly.  Your best bet for building something is going to be starting from 00da2c1c5d9cca517b80b98f4457467651f0d03c, which is the last commit to include 2.0.14.

However, you might have an easier time with 5d31a1e20371873affd9ce8ea630aedb94618471 (which is the last commit to still include 2.0 at all) or even trying to take the current 2.1 and downgrading it to 2.0.14.
