### ISSUE TITLE
Dockerfile will not build ha.pool.sks-keyservers.net DNS is dead

### ISSUE THREAD

**Issue by f15hb0wn** [docker-library/cassandra#234]
DNS records for pool.sks-keyservers.net are dead (see: sks-keyservers.net for details.) This prevents GPG key import and docker build to fail. List of active keyservers can be found here: https://sks-keyservers.net/status/. 

docker build will fail on L110 of Dockerfile. This effects 4.0rc2 and all previous Dockerfile versions

**Comment by wglambert** [comment]
Fixed with https://github.com/docker-library/cassandra/commit/6d3117157c726a7d3a8667f56e6fb046cfe18106
And pushed to Dockerhub in https://github.com/docker-library/official-images/pull/10458
