### ISSUE TITLE
gpg: keyserver receive failed: Server indicated a failure

### ISSUE THREAD

**Issue by binbinshi** [docker-library/cassandra#239]
C* 3.11.11 local build image
error :
 + gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
 gpg: keybox '/tmp/tmp.UiN4MdZNZ1/pubring.kbx' created
 gpg: keyserver receive failed: Server indicated a failure

anyone help , thank you

**Comment by wglambert** [comment]
See https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification (especially https://github.com/tianon/pgp-happy-eyeballs)

https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

You could keep running the build and it should eventually succeed

Also `FROM cassandra` might be an option for you, so as to not have to rebuild the image that's already published and just modifying it from there

**Comment by tianon** [comment]
This is weird -- https://keys.openpgp.org has been _very_ stable for us. :confused:

**Comment by binbinshi** [comment]
thanks，everybody ; I waited a few days and tried again, now it work ; i think gpg keyservers service unstable。
