### ISSUE TITLE
Handle rpc_address in docker-entrypoint.sh

### ISSUE THREAD

**Issue by blop** [docker-library/cassandra#25]
We can currently configure easily those parameter from the cassandra.yaml : 
		broadcast_address
		broadcast_rpc_address
		cluster_name
		endpoint_snitch
		listen_address
		num_tokens

**rpc_address** should be added to be complete, otherwise it defaults to 0.0.0.0.

**Comment by yosifkit** [comment]
The `0.0.0.0` is set in the [Dockerfile](https://github.com/docker-library/cassandra/blob/f1324a4a0938e3eb9f6c40f2065694f4dd22f719/2.2/Dockerfile#L16-L18) to make it [listen on all interfaces](http://docs.datastax.com/en/cassandra/1.2/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__rpc_address); which, in the usual container setup, is just the connection to the bridge and localhost.  When would this need to be overridden?

**Comment by blop** [comment]
In case you want to run with net=host, to have better network performance.
I want to bind to a specific address of the host.

Plus, this is more consistent as there is already the possibility to configure the listen_address.
