### ISSUE TITLE
"The Java thread stack size specified is too small. Specify at least 384k" for ppc64le arch

### ISSUE THREAD

**Issue by Mathieu-Ferraton** [docker-library/cassandra#251]
Running `cassandra:4` on ppc64le produces this error: `The Java thread stack size specified is too small. Specify at least 384k`. 

Looking at the `ppc64le` specific section of the 4.0 Dockerfile, substitution of the `-Xss256k` value with `-Xss512k` is tried in `$CASSANDRA_CONF/jvm.options` file (3.11 legacy, file doesn't exists in 4.0), and in `$CASSANDRA_CONF/cassandra-env.sh` (3.0 legacy, option not set from there in 4.0):

https://github.com/docker-library/cassandra/blob/dee264d35d3efd9aa8368742605d2e48979ec1b1/4.0/Dockerfile#L143-L158 

In cassandra 4.0, setting `-Xss256k` in `JVM_OPTS` is done in `$CASSANDRA_CONF/jvm-server.options`, so the corresponding Dockerfile should reflect that change.

**Comment by tianon** [comment]
Fixed via https://github.com/docker-library/cassandra/pull/252
