### ISSUE TITLE
Cassandra's amd64 images seem broken starting with 3.11.16

### ISSUE THREAD

**Issue by konstantinwirz** [docker-library/cassandra#274]
Cassandra amd64 images have broken java runtime. 3.11.15 works just fine and starting with 3.11.16 all images seem broken. "focal" to "jammy" update might be the cause. arm64 isn't affected, amd64 only.  

```shell
$ docker run --rm cassandra:3.11.16 java
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create GC thread. Out of system resources.
# An error report file with more information is saved as:
# //hs_err_pid1.log
$ uname -a
Linux runner-dw3mthb5-project-1637-concurrent-0-fskop8ub 4.14.330-250.540.amzn2.x86_64 #1 SMP Tue Nov 21 09:57:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yosifkit** [comment]
If the update from `focal` to `jammy` is the culprit then it is `libseccomp on the host: https://github.com/docker-library/tomcat/issues/269#issuecomment-1170461034 https://github.com/docker-library/mongo/issues/606#issuecomment-1424965831 (similar to the Debian Bullseye to Bookworm updates in other images https://github.com/docker-library/python/issues/837#issuecomment-1599640563).

You can verify that the update to `jammy` is the likely cause by running the container with `--security-opt seccomp=unconfined`. If it works, then the solution is to update Docker and libseccomp on the host.

**Comment by konstantinwirz** [comment]
many thanks! can confirm it's working with focal images.
