### ISSUE TITLE
support minor versions (2.2.2)

### ISSUE THREAD

**Issue by vincentlaucy** [docker-library/cassandra#29]
My use case for the image is to run the `cqlsh`
the udpated 2.2.3 uses `3.3.1` protocol, which I can't connect to the server which is still using `3.3.0`
on the other hand `2.1` will also be too old

Is it also possible to support minor versions in docker hub?
(It is honestly a problem how cassandra handle version compatibility, but if this image help solve the issue it will be great)

```
Connection error: ('Unable to connect to any servers', {'1.1.1.1': ProtocolError("cql_version '3.3.1' is not supported by remote (w/ native protocol). Supported versions: [u'3.3.0']",)})
```

**Comment by vincentlaucy** [comment]
and seems another problem is it is even no longer available at `apt-get`?

**Comment by yosifkit** [comment]
Old versions are not deleted from the hub: https://hub.docker.com/r/library/cassandra/tags/; they just become "unsupported", but are still available for `docker pull`.
