### ISSUE TITLE
Support setting a seed provider

### ISSUE THREAD

**Issue by hseeberger** [docker-library/cassandra#36]
Instead of setting fixed seed nodes Cassandra allows setting a seed provider, see http://docs.datastax.com/en/cassandra/2.2/cassandra/configuration/configCassandra_yaml.html?scroll=configCassandra_yaml__seed_provider for details.

I suggest to add a CASSANDRA_SEED_PROVIDER env variable. If that is set, ignore CASSANDRA_SEEDS and instead rewrite configuration along the lines of:

```
seed_provider:
    - class_name: $CASSANDRA_SEED_PROVIDER
```

**Comment by analytically** [comment]
:+1:

**Comment by tianon** [comment]
I think the discussion over on the PR starting at https://github.com/docker-library/cassandra/pull/39#issuecomment-169093871 is probably a good read (I'll refrain from copying it here). :smile: :+1:
