### ISSUE TITLE
Tables are empty after restart

### ISSUE THREAD

**Issue by hotstepper13** [docker-library/cassandra#42]
We are using the docker image for our 2 node cluster. It will be started by mesos/marathon with the following command:

    docker run --rm -m 800m --name cassandra-`hostname` -v /data/cassandra/smile:/var/lib/cassandra/data -e CASSANDRA_CLUSTER_NAME=smile-database -e CASSANDRA_BROADCAST_ADDRESS=`hostname` -p 7000:7000 -p 9160:9160 -p 9042:9042 -p 7199:7199 -e CASSANDRA_SEEDS=<hostname1>,<hostname2> cassandra:2.2.1

After that we are able to create a keyspace and inserting data. Everything looks fine. Data is synchronized between the nodes and available to the clients that are connecting.

After a restart which means also spawning a new container, the keyspace is still existing but all the tables are empty.

After reading the documentation at http://docs.datastax.com/en/cassandra/2.0/cassandra/dml/dml_write_path_c.html

it look like as if the data is not flushed to the disc. The content of my keyspace directory (find .) looks like:

    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/la-1-big-Statistics.db
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/la-1-big-TOC.txt
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/la-1-big-Data.db
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/backups
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/la-1-big-CompressionInfo.db
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/la-1-big-Index.db
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/la-1-big-Summary.db
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/la-1-big-Filter.db
    ./lounge_offer_by_id-dd3708508cec11e5af9b091830ac5256/la-1-big-Digest.adler32
    ./lounge_capacity-e3eb94b07bf111e590f8091830ac5256
    ./lounge_capacity-e3eb94b07bf111e590f8091830ac5256/backups
    ./lounge_offer_opened-e30b46d07bf111e590f8091830ac5256
    ./lounge_offer_opened-e30b46d07bf111e590f8091830ac5256/backups
    ./lounge_offer_pending-e2d2f8c07bf111e590f8091830ac5256
    ./lounge_offer_pending-e2d2f8c07bf111e590f8091830ac5256/backups
    ./lounge_details-e35548207bf111e590f8091830ac5256
    ./lounge_details-e35548207bf111e590f8091830ac5256/.lounge_type_index
    ./lounge_details-e35548207bf111e590f8091830ac5256/backups
    ./lounge_details-e35548207bf111e590f8091830ac5256/backups/.lounge_type_index
    ./lounge_details-de0be4808cec11e5af9b091830ac5256
    ./lounge_details-de0be4808cec11e5af9b091830ac5256/.lounge_type_index
    ./lounge_details-de0be4808cec11e5af9b091830ac5256/backups
    ./lounge_details-de0be4808cec11e5af9b091830ac5256/backups/.lounge_type_index
    ./lounge_capacity-de5633f08cec11e5af9b091830ac5256
    ./lounge_capacity-de5633f08cec11e5af9b091830ac5256/backups
    ./opened_lounge_offer_by_lounge-dde856f08cec11e5af9b091830ac5256
    ./opened_lounge_offer_by_lounge-dde856f08cec11e5af9b091830ac5256/backups
    ./lounge_offer_sent-e33404807bf111e590f8091830ac5256
    ./lounge_offer_sent-e33404807bf111e590f8091830ac5256/backups
    ./offer_by_lounge_type_and_airport_code-ddab4df08cec11e5af9b091830ac5256
    ./offer_by_lounge_type_and_airport_code-ddab4df08cec11e5af9b091830ac5256/backups
    ./lounge_offer_by_focus_id-dd5873008cec11e5af9b091830ac5256
    ./lounge_offer_by_focus_id-dd5873008cec11e5af9b091830ac5256/backups
    ./opened_lounge_offer-ddc6c5308cec11e5af9b091830ac5256
    ./opened_lounge_offer-ddc6c5308cec11e5af9b091830ac5256/backups
    ./pending_lounge_offer-dd8947008cec11e5af9b091830ac5256
    ./pending_lounge_offer-dd8947008cec11e5af9b091830ac5256/backups

There are snapshot directories that i excluded from this output.

Any hints are highly appreciated :)

**Comment by hotstepper13** [comment]
I managed to fix this by myself.

In the documentation on docker hub there is the followng "mount configuration" mentioned:
    -v /my/own/datadir:/var/lib/cassandra/data

Because commitlog will be saved at /var/lib/cassandra/commitlog it will not be saved on the host.

I solved the problem by changing the mount to
    -v /my/own/datadir:/var/lib/cassandra

Now it works as expected.

**Comment by tianon** [comment]
Doh, looks like https://github.com/docker-library/cassandra/commit/57ac886ee508f5e82dce0035ed71eb3bb55a7114 didn't propagate to the docs appropriately!  Good catch. :+1:
