### ISSUE TITLE
Cassandra 2.1.11 doesn't start in docker 1.9.1

### ISSUE THREAD

**Issue by mlardeur** [docker-library/cassandra#43]
Pulling from the official image, cassandra doesn't seems to start and hang the container. Starting a Single node cluster:

    docker run --name dev-cassandra -d cassandra:2.1

Wait for a while to be shure cassandra is started and start a new linked container to run cqlsh

    docker run -it --link dev-cassandra:cassandra --rm cassandra:2.1 cqlsh cassandra

    Connection error: ('Unable to connect to any servers', {'cassandra':    error(111, "Tried connecting to [('172.17.0.2', 9042)]. Last error: Connection refused")})

then no way to kill or remove the container (restart of the machine needed)

    docker kill dev-cassandra
    docker rm -f dev-cassandra

The cassandra 2 & 3 just work fine

    docker run --name latest-cassandra -d cassandra:latest

Then waiting for the cassandra to be ready:
    
    docker run -it --link latest-cassandra:cassandra --rm cassandra:latest cqlsh cassandra

    Connected to Test Cluster at cassandra:9042.
    [cqlsh 5.0.1 | Cassandra 3.0.0 | CQL spec 3.3.1 | Native protocol v4]
    Use HELP for help.
    cqlsh>

My Configuration is:

Docker (Server Version: 1.9.1, Kernel Version: 4.1.13-boot2docker)
Yosemite
VirtualBox 5.0.10

**Comment by raimille1** [comment]
+1 here, I'm facing the same situation

**Comment by yosifkit** [comment]
In testing this, the initial cassandra server sometimes took a bit before it would accept connections, so there were some "connection refused".  Are you still having this problem?

**Comment by gtaylor** [comment]
No, in our case Cassandra just never starts. It hangs in this in-between state indefinitely. 

The Cassandra 2.2 images seem to not have this issue, though.

**Comment by yosifkit** [comment]
Anything useful in `docker logs`?  It is only when using OSX and the VM?  My first thought is that the VM might not have the memory or hard drive space that cassandra needs it to have (most places recommend 4GB minimum for cassandra).

**Comment by gtaylor** [comment]
```docker logs``` showed no output. This is with a 4 core 16 GB Google Cloud VM.

**Comment by dmcquay** [comment]
Hitting this too.

**Comment by yosifkit** [comment]
This intuitively looks like https://github.com/docker/docker/issues/18180.  So using somethings beside `aufs` or using the handy chart: https://github.com/docker/docker/issues/18180#issuecomment-173436661 could solve the problem.

**Comment by krishna81m** [comment]
@yosifkit, not sure if my issue is related to this, i.e., ulimit issue or should I not be running service cassandra start to verify what is going wrong at all?:
https://github.com/docker-library/cassandra/issues/46

**Comment by krishna81m** [comment]
I am able to run pocklet/cassandra (https://github.com/pokle/cassandra/blob/master/cassandra/Dockerfile) which uses centos and according to https://github.com/docker/docker/issues/18180#issuecomment-173436661, can we upgrade the debian version on docker/cassandra to fix the issue as you recommended?

```
docker/cassandra uses debian:jessie-backports

docker run --name cassandra-with-schema-data-thrift-v2 --ulimit nofile=10000:10000 -v //c/Users/docker-workspace/shared:/shared -d cassandra-with-schema-data-thrift-v2
docker ps
winpty docker exec -it 154d46b18071 bash


cqlsh
and everything else works just fine
```

**Comment by tianon** [comment]
This is definitely a kernel bug (specifically in the AUFS code), so there's nothing to change in the image.  If you're running into this issue, you need to upgrade your kernel (or upgrade the version of the AUFS patches you're using, if you compile your own kernel).

**Comment by 1605200517** [comment]
on Ubuntu, with Docker 17.03.1-ce:
/etc/init.d/cassandra: 72: ulimit: error setting limit (Operation not permitted)
(tried to install and run cassandra 3.0.9 with Oracle JDK 1.8)
