### ISSUE TITLE
occasionally see this error: "error setting limit (Operation not permitted)" on my windows machine

### ISSUE THREAD

**Issue by krishna81m** [docker-library/cassandra#46]
New to Docker, docker-library/cassandra ran fine on my windows laptop until I restarted, now I see this error after starting a container and don't remember making any changes. This probably has not to do with cassandra image itself but I don't see a way to set it on container.

This only sets it on the image.
```
docker -d --default-ulimit nproc=1024:2048

This will set a soft limit of 1,024 and a hard limit of 2,048 child processes for all containers. You can set this option multiple times for different ulimit values: --default-ulimit nproc=1024:2408 --default-ulimit nofile=100:200
```

```
root@34d4b228cd55:/# cat /etc/security/limits.d/cassandra.conf
# Provided by the cassandra package
cassandra  -  memlock  unlimited
cassandra  -  nofile   100000
cassandra  -  as       unlimited
cassandra  -  nproc    8096
root@34d4b228cd55:/# service cassandra status
Cassandra is not running.
root@34d4b228cd55:/# service cassandra start
/etc/init.d/cassandra: 71: ulimit: error setting limit (Operation not permitted)
root@34d4b228cd55:/# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7893
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1048576
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

```

Environment: Windows 7 laptop

```
$ docker version
Client:
Version: 1.9.0
API version: 1.21
Go version: go1.4.3
Git commit: 76d6bc9
Built: Tue Nov 3 19:20:09 UTC 2015
OS/Arch: windows/amd64

Server:
Version: 1.9.1
API version: 1.21
Go version: go1.4.3
Git commit: a34a1d5
Built: Fri Nov 20 17:56:04 UTC 2015
OS/Arch: linux/amd64

$ docker info
Containers: 32
Images: 279
Server Version: 1.9.1
Storage Driver: aufs
Root Dir: /mnt/sda1/var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 343
Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: AXXY:B6JJ:6M6W:LXME:VWED:BNEA:4MKU:LDP5:TWKR:CCUH:3SKV:BSBE
Debug mode (server): true
File Descriptors: 28
Goroutines: 46
System Time: 2016-01-16T02:28:33.17774389Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
provider=virtualbox
```

**Comment by krishna81m** [comment]
Tried changing by stopping the VM, but could not!
```
MINGW64 ~
$ docker-machine stop default

MINGW64 ~
$ ulimit -n 16000
bash: ulimit: open files: cannot modify limit: Too many open files
```

**Comment by yosifkit** [comment]
- `/etc/security/limits.d/` isn't checked by docker that is for `pam_limits`
 - why are you trying to `service cassandra start` in a container?  A container is a single process space, there is no `init` system running.
 - running `ulimit -n 16000` in the mingw terminal wouldn't affect the VM, unless you have ssh'd in, and even then would not affect any containers but only future child processes of that ssh shell session.

Not sure why the VM would suddenly change, but you can set ulimits per container.

```console
$ docker run --ulimit nproc=1024:2048 -d cassandra
```

Does that help solve your problem?

**Comment by yosifkit** [comment]
Alternatively, if you don't have anything important on the docker VM, you could go the extreme route and try blasting it away and creating a new one:
```console
$ docker-machine rm default
$ docker-machine create --driver virtualbox default
```

**Comment by krishna81m** [comment]
Because, cassandra was not starting "and had no logs" when container started, I was trying to find why, i.e., by doing service cassandra start. Did not quite understand why you should not run any services inside a container though?

Are you saying container cassandra process does not look at container ulimits?

Yes, as mentioned first, was aware of docker run, but my container was already up, so, was trying to find if ulimits in host machine (windows laptop) or in container can fix it. Also, I cannot commit that container to an image or stop it and have created a ticket before this one.
https://github.com/docker/docker/issues/19578

Looks like I have to commit an image and run again or removing machine itself.

**Comment by yosifkit** [comment]
The way cassandra is run in the container is a a single process, ie `cassandra -f`.  That is it, nothing else is running in that container except what child processes `cassandra -f` may spawn.  If you did a `docker exec -it my-cassandra bash` into the current cassandra container then there would now be a bash process in the container.  Running `service cassandra status` in the `docker exec` shell would not show it as running since it was not started through the init system (and there is no init system even running).  You should be able to `ps aux` in the `docker exec` and see the cassandra process there.

For ulimits, because of the way containers are limited, you cannot set ulimits from within the container, but the docker daemon running in the VM has a flag to set the default ulimit for new containers (which can be added in [`/var/lib/boot2docker/profile` in the VM](https://stackoverflow.com/questions/26424338/docker-daemon-config-file-on-boot2docker)).  You can also specify the limit when starting a container (`--ulimit`).  Any ulimit that you set in windows would be unseen by the docker daemon.

As far as the container not stopping, that looks like https://github.com/docker/docker/issues/18180. Which versions of Linux that have fixes can be found here: https://github.com/docker/docker/issues/18180#issuecomment-173436661.

What changes in the container are you worried about loosing?  If it is just the database files that you need to save and this container is having issues, then a `docker run --volumes-from old-cassandra --name new-cassandra -d cassandra` should get you a new cassandra container that is using the old databases files from `/var/lib/cassandra`.  I would then restart the VM (or host) to get the old one to stop. Then a `docker start new-cassandra` should get that new one up.  If there are other changes to the container I would recommend using a `Dockerfile` rather then shelling into the container and changing configuration.

**Comment by krishna81m** [comment]
Got it, that is because cassandra is started using exec which replaces current program with the process without spawning a new process like it regularly does when you do service cassandra start. But, why would you do that? isn't service or init.d the right way?
https://raw.githubusercontent.com/docker-library/cassandra/master/2.1/docker-entrypoint.sh

Also, how do I set ulimits at a global level in windows docker bash? Will everything be okay if I have multiple containers with unlimited ulimits?

How do I set ulimits on my windows docker host globally, don't see /etc/security/limits.conf or docker.conf?
MINGW64 ~
$

**Comment by krishna81m** [comment]
The saga continues, tried specifying ulimits, I get "Unable to connect to any servers" :

```
MINGW64 /
$ docker run --name krishna-cassandra-2.1.12-v1 --ulimit nofile=10000:10000 -v //c/Users/docker-workspace/shared:/shared -d cassandra:2.1.12
b05dcf623c954f2b9213e5371d658924a07fe5598c78173bde3d2b2a8d41fb62

MINGW64 /
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                         NAMES
b05dcf623c95        cassandra:2.1.12    "/docker-entrypoint.s"   5 seconds ago       Up 3 seconds        7000-7001/tcp, 7199/tcp, 9042/tcp, 9160/tcp   krishna-cassandra-2.1.12-v1

MINGW64 /
$ winpty docker exec -it b05dcf623c95 bash
root@b05dcf623c95:/# cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [
('127.0.0.1', 9042)]. Last error: Connection refused")})
root@b05dcf623c95:/# ps -aef | grep cassandra
root         1     0  0 06:32 ?        00:00:00 /bin/sh /usr/sbin/cassandra -f
root        74    60  0 06:35 ?        00:00:00 grep cassandra
root@b05dcf623c95:/# tail -f /var/log/cassandra/*
tail: cannot open '/var/log/cassandra/*' for reading: No such file or directory
tail: no files remaining
root@b05dcf623c95:/# ls -ltrh /var/log/cassandra/*
ls: cannot access /var/log/cassandra/*: No such file or directory
root@b05dcf623c95:/#
```

**Comment by krishna81m** [comment]
I give up on existing debian containers and started setting up my own 
ubuntu image and it gets stuck at:
```
Setting up cassandra (2.1.12) ...
Adding group `cassandra' (GID 106) ...
Done.
sysctl: setting key "vm.max_map_count": Read-only file system
sysctl: cannot stat /proc/sys/net/ipv4/tcp_keepalive_time: No such file or directory

Warning: unable to set vm.max_map_count; is this an OpenVZ
instance? If so, it is highly recommended that you set
vm.max_map_count to 1048575 in the host.

Deleting the local sysctl.d/cassandra.conf.
removed '/etc/sysctl.d/cassandra.conf'
invoke-rc.d: policy-rc.d denied execution of start.
Setting up ca-certificates-java (20130815ubuntu1) ...
```

**Comment by krishna81m** [comment]
On centos, I installed the tarball and java manually, and it seems stuck starting? I cannot even kill this. Is it because I have two docker terminals in windows?

```
Complete!
[root@95be11112fd5 opt]# java -version
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
[root@95be11112fd5 opt]# $CASSANDRA_PATH/bin/cassandra -p $CASSANDRA_PATH/cassandra.pid

```

Tried this from another terminal and it does not work:

```
 docker stop 95be11112fd5
```

**Comment by krishna81m** [comment]
Downgraded to 1.9 and everything works fine:
https://github.com/boot2docker/boot2docker/issues/1099#issuecomment-174440791

**Comment by yosifkit** [comment]
The containers failing to start and unable to kill are the `aufs` bug. My guess is that it could have been also contributing to the ulimit errors.
