### ISSUE TITLE
Multi DC Support through environment variables

### ISSUE THREAD

**Issue by alexanderjardim** [docker-library/cassandra#5]
We should add the following environment variables to this image

### `CASSANDRA_DC`
This variable sets the datacenter name of this node. Defaults to `DC1`
(it should change `cassandra-rackdc.properties`)

### `CASSANDRA_RACK`
This variable sets the rack name of this node. Defaults to `RAC1`
(it should change `cassandra-rackdc.properties`)

### `CASSANDRA_ENDPOINT_SNITCH`
This variable sets the snitch implementation this node will use. Defaults to `SimpleSnitch`
(it should change `cassandra.yml`)

These are the minimum setup we need to do to get a multi datacenter compatible cluster with this Cassandra image.

**Comment by yosifkit** [comment]
That sounds good to me.  Would you want to make a PR to update the [docker-entrypoint](https://github.com/docker-library/cassandra/blob/master/docker-entrypoint.sh) to handle them?  And if you are feeling extra ambitious, a second PR to update the [docs](https://github.com/docker-library/docs/blob/master/cassandra/content.md)?
