### ISSUE TITLE
Using external data store in windows fails

### ISSUE THREAD

**Issue by chavolla** [docker-library/cassandra#54]
When using the option to mount a volume for data storage, cassandra is not able to wite logs and stops. The instruction used is 

`docker run --name myCass2 --rm -v //c/cassandra_storage:/var/lib/cassandra -it cassandra:2.2`

and the error: 

`ERROR 23:05:11 Exiting due to error while processing commit log during initialization.
org.apache.cassandra.io.FSWriteError: java.io.IOException: Invalid argument`

I tried with Cassandra 2.2 and 3.3 and it is the same. Using store inside the image woks perfectly

**Comment by yosifkit** [comment]
I think with the most recent change we need to `chown`/`chmod` the logs folder in the Dockerfile.  Also the default with docker-machine is to only share the `Users/` directory, so the bind mount will have to use that and will probably need `--user` similar to https://github.com/docker-library/cassandra/pull/48#issuecomment-175224778

**Comment by chavolla** [comment]
got the latest version and just tried as indicated in the link, but no luck so far. Tried
`docker run --name myCass2 --rm -v //c/cassandra_storage:/var/lib/cassandra --user 1000:50 -it cassandra:latest`
 The error remains, not sure if I should try a different user or different mounting path

**Comment by tianon** [comment]
We do `chown` and `chmod` in the `Dockerfile` (as of https://github.com/docker-library/cassandra/pull/48), so if this isn't fixed now, I don't think there's actually anything we can realistically do about it.  It might be that Cassandra doesn't support the kind of filesystem access `vboxsf` provides.  It _might_ be possible using Docker for Windows (given that it uses an alternate file-sharing implementation that's more forgiving about permissions issues), but it's hard to say for sure without testing it.  Sorry!
