### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by mrsanuk** [docker-library/cassandra#61]
Hi, I use cassandra:3.0.4 and have next warning messages in the logs

```
WARN  11:50:19 Small commitlog volume detected at /var/lib/cassandra/commitlog; setting 
WARN  11:50:19 Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.
WARN  11:50:19 jemalloc shared library could not be preloaded to speed up memory allocations
WARN  11:50:19 OpenJDK is not recommended. Please upgrade to the newest Oracle Java release
```

I disabled swap on the host, and changed resource limits in container to 

```
/etc/security/limits.d/cassandra.conf

<cassandra_user> - memlock unlimited
<cassandra_user> - nofile 100000
<cassandra_user> - nproc 32768
<cassandra_user> - as unlimited

/etc/sysctl.conf:

vm.max_map_count = 131072
```

but still have this messages. 
Can somebody help me?

**Comment by eddytruyen** [comment]
I am also trying to run a Docker Cassandra container without these warnings. 
I am trying to get rid of the unable lock JVN memory error too but I didn't solve it either.
Have you already found a solution.

I changed the container as well by installing the recommended Oracle JDK instead of OpenJDK.

**Comment by yosifkit** [comment]
@eddytruyen is correct, the docker daemon sets some ulimits by default that are then inherited by created container processes, so you need to set the ulimits directly on the docker daemon (via upstart, systemd, etc). But you should also be able to use the `ulimit` flag on docker run, https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit.

```console
$ docker run -it --rm --ulimit memlock=819200000 debian sh -c 'ulimit -a'
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     0
memory(kbytes)       unlimited
locked memory(kbytes) 800000
process              unlimited
nofiles              1048576
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
```
