### ISSUE TITLE
cassandra configurations don't update when container's IP address is changed after restarts

### ISSUE THREAD

**Issue by mhariri** [docker-library/cassandra#67]
Docker containers can get different IP addresses in between restarts. Cassandra entry point script does not support updating configurations with the new IP addresses, and that causes problems when a container is restarted, especially if the previous address is offered to a new cassandra instance, then current instance tries to make a cluster with the other one if restarted.

**Comment by tianon** [comment]
In reading the script, the only IP address that doesn't appear to be updated on restart would be `CASSANDRA_SEEDS` (it's the only one for whom the `sed` expression includes the default value, explicitly so that we do not update the config).

Can you provide a bit more detail on the issue so we can try to reproduce?

**Comment by mhariri** [comment]
About updating the config, you are right, it's only that, but I thought it would be cleaner to make sure that we make the process stateless, so it always takes the same original config file and changes it.

About steps to reproduce, I can easily reproduce it with following steps:

1. `docker run -d --name c1 cassandra`
2. `docker stop c1`
3. `docker run -d --name c2 cassandra`
4. `docker restart c1`
5. `docker exec -it c1 /bin/bash`
6. `ip addr show`
7. `grep seeds /etc/cassandra/cassandra.yaml`

Expected behaviour:
The IP address of the container (step 6) should be the same as the seed address (step 7)

Actual behaviour:
The IP address of the seed is different than the current IP address of the container

**Comment by mhariri** [comment]
The fix is waiting to be merged at #68
