### ISSUE TITLE
Add Cassandra 3.7

### ISSUE THREAD

**Issue by mzbyszynski** [docker-library/cassandra#70]
Hi There!

Cassandra 3.6 + 3.7 have been released. Could we add them to this container? I am happy to submit a PR for this, I just need to know if 3.7 should be a new tag or if it should replace 3.5?

Thanks!
-Marc

**Comment by yosifkit** [comment]
Thanks that would be great.  From the cassandra downloads page it looks like `3.5` is not supported since it was the last odd release, so we should replace it with `3.7`.  I don't think we need `3.6` since `3.7` is just bug fixes on top of `3.6`.
