### ISSUE TITLE
can not import or export .csv from docker container to local machine

### ISSUE THREAD

**Issue by DaniyalGeek** [docker-library/cassandra#73]
i am using cassandra 2.2  and use cqlsh from cotainer by following
`COPY dbname.tablename TO ' file.csv'`

i dont know to to get this csv file by giving exact path

**Comment by yhh2013060108** [comment]
Start your cassandra container like this(needs to make sure that the directory '~/data' exists):
docker run --name some-cassandra -v ~/data:/data -d cassandra:tag
then use cqlsh from container by following:
COPY dbname.tablename TO '/data/file.csv'
and you can find the csv file you want in '~/data' directory.
forgive me,this is my first comment and I'm not good at English.

**Comment by DaniyalGeek** [comment]
Yes got it you can close this issue now.
