### ISSUE TITLE
JMX port is not enabled and hence nodetool is not working in the containers

### ISSUE THREAD

**Issue by Codess2015** [docker-library/cassandra#78]
JMX port should be enable. Tools like cassandra-stress and node-tools are not using all the nodes in the cluster.

**Comment by yosifkit** [comment]
So what needs to be added or is it just an env var that is evaluated by `cassandra_env.sh`?

**Comment by Codess2015** [comment]
env var in cassandra_env.sh and few more steps. 
1) set $LOCAL_JMX to "no" before this var is used in cassandra_env.sh
2) Update jmxremote.password and jmxremote.access file to include cassandra user
3) Set correct permission on jmxremote.password and jmxremote.access

Here is the complete reference - https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/secureJmxAuthentication.html

**Comment by jortkoopmans** [comment]
I've also hit this problem today. As Codess2015 describes, even while the JMX is enabled, it is configured by default to only work on localhost (without credentials). 
There does not seem to be a good way to provide this information via the docker container environment, the only workarounds are either modifying the image or mapping a manually modified cassandra_env.sh (and jmxremote.*) file(s) to the container.

When remote JMX is enabled, authentication is also required.
From cassandra_env.sh:
```shell
if [ "$LOCAL_JMX" = "yes" ]; then
  JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.local.port=$JMX_PORT"
  JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
else
  JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.remote.port=$JMX_PORT"
  JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT"
  JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=true"
fi
```

I've tried to use:
-e "LOCAL_JMX=no"
which did seem to change the behaviour (still get a timeout), but not sure how to modify auth behaviour outside of the container.

**Comment by cmlicata** [comment]
@Codess2015 and @jortkoopmans, in my experience, for remote jmx, you also want to set `JVM_OPS="$JVM_OPS -Djava.rmi.server.hostname=$IP_ADDRESS`.  This will allow you to run nodetool on other nodes.

**Comment by megastef** [comment]
Is this already solved? Why don't you open JMX port for external connections by default? Docker user can decide if they expose the port or not. I found this image, having some JMX options: https://github.com/oberthur/docker-cassandra

**Comment by yosifkit** [comment]
To setup remote JMX, you should be following something similar these steps https://support.datastax.com/hc/en-us/articles/204226179-Step-by-step-instructions-for-securing-JMX-authentication-for-nodetool-utility-OpsCenter-and-JConsole.  There is quite a bit more than *just* username and password that we should not be auto-configuring in the image.
