### ISSUE TITLE
limit memory usage and adding authentication and authorization options

### ISSUE THREAD

**Issue by KamyarM** [docker-library/cassandra#81]
How to limit the memory usage of each Cassandra nodes for development purposes? Is there any environment variable? Also it is nice if the Authentication and Authorization options are added since it is pretty easy by minor modification of docker-entrypoint.sh file  so no more branching from this official image is needed.

**Comment by seeeking** [comment]
Do we have an answer for this?

**Comment by flippakitten** [comment]
@seeeking there is a solution if you, or anyone else that happens to find this.

environment:
    MAX_HEAP_SIZE: 128M
    HEAP_NEWSIZE: 24M
mem_limit: 512m

**Comment by tianon** [comment]
Indeed -- this is a configuration question (which is mostly answered above). :+1:

For further help, I'd recommend checking the Cassandra docs for the necessary configuration to accomplish your desires.
