### ISSUE TITLE
cannot connect cqlsh from different container for 2.1.16 image

### ISSUE THREAD

**Issue by jigarshah** [docker-library/cassandra#90]
```
$  docker run -it --link node1:cassandra --rm cassandra sh -c 'exec cqlsh "$CASSANDRA_PORT_9042_TCP_ADDR"'
Connection error: ('Unable to connect to any servers', {'172.17.0.2': DriverException('ProtocolError returned from server while using explicitly set client protocol_version 4',)})
```

As per some search it seems cqlsh version incompatibility ? 

https://github.com/intuit/wasabi/issues/98

I am running image 2.1.16

As per 
https://docs.datastax.com/en/landing_page/doc/landing_page/compatibility.html

It should be 3.1

on container if I do cqlsh it show. 
[cqlsh 5.0.1 | Cassandra 2.1.16 | CQL spec 3.2.1 | Native protocol v3]

Please guide if I am missing anything

**Comment by yosifkit** [comment]
I would guess that you need to run the same image of cassandra on the client and server:
```console
$ # if your server was started like this:
$ docker run -d [other-docker-args] cassandra:2.1.6
$ # then you need to run cqlsh from the same image:
$ docker run -it --link node1:cassandra --rm cassandra:2.1.6 sh -c 'exec cqlsh "$CASSANDRA_PORT_9042_TCP_ADDR"'
```
