### ISSUE TITLE
Docker Cloud initialization option

### ISSUE THREAD

**Issue by tracker1** [docker-library/cassandra#93]
It would be nice to have an in the box option for initializing a C* service in docker cloud.

There's an option to sequentially start the servers, which would allow the `foo-1` service to know it's the first node in the `foo` cluster... and each progressive instance can then know it is `foo-N` and to talk to `foo-1`

**Comment by yosifkit** [comment]
That is not something that upstream provides and we try to keep as close to their recommendations as possible.  We do have a set of instructions on [setting up a cluster](https://github.com/docker-library/docs/tree/b5f890c5f7a8909cc72e2c5787a4ba01a9cb2a73/cassandra#make-a-cluster), which could be adapted with some scripting to use something like Consul or etcd to discover already started nodes and auto-join a cluster.
