### ISSUE TITLE
Cassandra 3.10

### ISSUE THREAD

**Issue by vvsh** [docker-library/cassandra#97]
Hi,

Cassandra 3.10 was released two weeks ago, but latest version is still 3.9.

Do you plan to update it?

Thanks,
Uladzimir

**Comment by tianon** [comment]
Thanks for the prod! :heart:

I took a stab at updating this, and ran into the following error: :confused:
```console
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cassandra : Depends: openjdk-8-jre-headless but it is not going to be installed or
                      java8-runtime
E: Unable to correct problems, you have held broken packages.
```

(which is odd because we're `FROM debian:jessie-backports`, and backports definitely has that package: https://packages.debian.org/jessie-backports/openjdk-8-jre-headless)

**Comment by tianon** [comment]
(Going to make it a PR so it's easier to see/test)

**Comment by tianon** [comment]
https://github.com/docker-library/cassandra/pull/98 :+1:
